Dev add comments
EstandaresDeCalidadSW23/vikingos-analyser pull request #36
Opened 2023-09-16 18:46 UTC by CarlosMoriel

Allow comments on the code with regex

2023-09-17 18:18 UTC, bcisneros requested changes
Please add the respective unit tests

2023-09-28 02:30 UTC, CarlosMoriel commented
to run all the test: 
`npm run test`

2023-09-28 02:39 UTC, karibeltran commented
Please close tickt if the task is already done
thank you

2023-09-28 02:41 UTC, bcisneros approved these changes
lgtm

2023-09-28 02:42 UTC, merged